alias cp="cp -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias np='nano -w PKGBUILD'
alias more=less
alias ..='cd .. && ls'
alias react='cd && cd Documents/web-dev/react'
alias brett='cd && cd Documents/brett'
alias spoke='cd && cd Documents/brett/react/dave_spoke/spoke'
alias c='clear'
alias igd='npm install && gatsby develop'
alias gd='gatsby develop'
alias gbs='gatsby build && gatsby serve'
alias gbug='git add . && git commit -m "bugfix" && git push origin master'
alias gnew='git add . && git commit -m "added section" && git push origin master'
alias gup='git fetch upstream && git checkout master && git merge upstream/master'
alias pb='react && cd purpleandbold/purpleandbold'
alias nfix='npm audit fix'
alias fr='react &&  open . && cd'
alias ls='ls -a'
alias sleeptimer='sleep 1900 && systemctl suspend'
alias wtfwm='brew services restart chunkwm && brew serviecs restart skhd'
alias gomlmode='cd && cd Documents/python/ml &&  pyenv activate'
alias gomiscmode='cd && cd Documents/python/misc && source bin/activate'
alias depython='pyenv deactivate'
alias vim='nvim'
alias startenv='cd && bash scripts/startUpEnv.sh'

